#!/usr/bin/python
# -*- coding: utf-8 -*-

"""db.py: Models and functions for accessing the database
   - using peewee orm
   - preferably have all SQL in this file

Author: Tomi.Mickelsson@iki.fi

http://docs.peewee-orm.com/en/latest/peewee/querying.html
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#postgres-ext
"""

from peewee import *
from playhouse.shortcuts import model_to_dict
from red import RedisDB
from datetime import datetime
import statistics


from flask import abort
import config

import logging
log = logging.getLogger("db")

if config.IS_SQLITE:
    # config.DATABASE_HOST is full path to sqlite file
    database = SqliteDatabase(config.DATABASE_HOST, pragmas={})
else:
    from playhouse.postgres_ext import PostgresqlExtDatabase, ArrayField, BinaryJSONField, BooleanField, JSONField
    # support for arrays of uuid
    import psycopg2.extras
    psycopg2.extras.register_uuid()

    database = PostgresqlExtDatabase(config.DATABASE_NAME,
        user=config.DATABASE_USER, password=config.DATABASE_PASSWORD,
        host=config.DATABASE_HOST, port=config.DATABASE_PORT)


# --------------------------------------------------------------------------
# Base model and common methods

from datetime import datetime, date
from peewee import Model
from playhouse.shortcuts import model_to_dict


class BaseModel(Model):
    """Base class for all database models."""

    # exclude these fields from the serialized dict
    EXCLUDE_FIELDS = []

    def serialize(self):
        """Serialize the model into a dict."""
        d = model_to_dict(self, recurse=False, exclude=self.EXCLUDE_FIELDS)
        d["id"] = str(d["id"]) # unification: id is always a string
        return d

    class Meta:
        database = database


def get_object_or_404(model, **kwargs):
    """Retrieve a single object or abort with 404."""

    try:
        return model.get(**kwargs)
    except model.DoesNotExist:
        log.warning("NO OBJECT {} {}".format(model, kwargs))
        abort(404)

def get_object_or_none(model, **kwargs):
    """Retrieve a single object or return None."""

    try:
        return model.get(**kwargs)
    except model.DoesNotExist:
        return None


# --------------------------------------------------------------------------
# USER

class User(BaseModel):

    # Should user.id be an integer or uuid? Both have pros and cons.
    # Since user.id is sensitive data, I selected uuid here.
    if not config.IS_SQLITE:
        id = UUIDField(primary_key=True)
        id.auto_increment = True # is auto generated by server

    email = TextField()
    password = TextField()
    first_name = TextField()
    last_name = TextField()
    role = TextField()
    if not config.IS_SQLITE:
        tags = ArrayField(TextField)
    else:
        tags = TextField()

    created = DateTimeField()
    modified = DateTimeField()

    EXCLUDE_FIELDS = [password] # never expose password


    def is_superuser(self):
        return self.role == "superuser"

    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name or '')

    def serialize(self):
        """Serialize this object to dict/json."""

        d = super(User, self).serialize()

        # add extra data
        d["fullname"] = self.full_name()
        d["tags"] = self.tags or [] # never None
        return d

    def __str__(self):
        return "<User {}, {}, role={}>".format(self.id,
                self.email, self.role)

    class Meta:
        db_table = 'users'


def get_user(uid):
    """Return user object or throw."""
    return get_object_or_404(User, id=uid)


def get_user_by_email(email):
    """Return user object or None"""

    if not email:
        return None

    try:
#         return User.select().where(User.email == email).get()
        # case insensitive query
        if config.IS_SQLITE:
            sql = "SELECT * FROM users where email = ? LIMIT 1"
            args = email.lower()
        else:
            sql = "SELECT * FROM users where LOWER(email) = LOWER(%s) LIMIT 1"
            args = (email,)
        return list(User.raw(sql, args))[0]

    except IndexError:
        return None


def query_users(page=0, limit=1000, search=None):
    """Return list of users. Desc order"""

    page = int(page or 0)
    limit = int(limit or 1000)

    q = User.select()
    if search:
        search = "%"+search+"%"
        q = q.where(User.first_name ** search | User.last_name ** search |
                User.email ** search)
    q = q.paginate(page, limit).order_by(User.id.desc())
    return q


# --------------------------------------------------------------------------
# MOVIE - just an example for CRUD API...

class Movie(BaseModel):

    #id - automatic

    title = TextField()
    director = TextField()

    created = DateTimeField()
    modified = DateTimeField()

    creator = ForeignKeyField(db_column='creator', null=True,
                    model=User, to_field='id')

    class Meta:
        db_table = 'movies'


def get_movie(id):
    """Return Movie or throw."""
    return get_object_or_404(Movie, id=id)


def query_movies(page=None, limit=None, search='', creator=None):
    """Return list of movies which match given filters."""

    page  = page or 0
    limit = limit or 1000

    q = Movie.select()

    if search:
        search = "%"+search+"%"
        q = q.where(Movie.title ** search | Movie.director ** search)

    if creator:
        q = q.where(Movie.creator == creator)

    q = q.paginate(page, limit).order_by(Movie.id)
    return q


def query_unique_directors():
    """Return list of unique directors. An example of a raw SQL query."""

    sql = "SELECT DISTINCT(director) FROM movies"
    rq = database.execute_sql(sql)
    return [x[0] for x in rq]


class City(BaseModel):

    #id - automatic

    name = CharField()
    code = CharField()

    class Meta:
        db_table = 'city'

    def get_city_by_code(code):
        if not code:
            return None
        city = City.get(City.code == code).dicts()
        return city

class Route(BaseModel):

    #id - automatic

    name = CharField()
    code = CharField()
    last_data_time = DateTimeField()
    city_id = ForeignKeyField(db_column='city_id', null=False, model=City, to_field='id')

    class Meta:
        db_table = 'route'

    def get_city_routes(city_id):
        if not city_id:
            return None
        routes = Route.select().where(Route.city_id==city_id).order_by(Route.id).dicts()
        return routes

    def get_city_routes_count(city_id):
        if not city_id:
            return None
        routes = Route.select().where(Route.city_id==city_id).count()
        return routes

    def get_city_routes_id(city_id):
        if not city_id:
            return None
        routes = Route.select(Route.id).where(Route.city_id==city_id).order_by(Route.id).dicts()
        return routes
    
    def get_route_by_code(code):
        if not code:
            return None
        route = Route.get(Route.code == code).dicts()
        return route

    def set_last_data_time(route_id):
        if not route_id:
            return None
        route = Route.update(last_data_time=datetime.now()).where(Route.id == route_id)
        res = route.execute()
        return res

    def prepare_route_last_data(route_id):
        if not route_id:
            return None
        route = get_object_or_none(Route, id=int(route_id))
        if not route:
            return None
        result = {}
        sensors = Sensor.get_route_sensors(route_id)
        sensor_ids = [item['id'] for item in sensors]
        reddb = RedisDB(route.city_id, route.id)
        last_data = reddb.last_route_snapshot(sensor_ids)
        result['route'] = model_to_dict(route)
        result['temp'] = None
        if last_data['temperature']:
            result['temp'] = last_data['temperature']['value']
        result['med_humidity'] = 0
        humidity_values = []

        for sensor in sensors:
            sensor_id = sensor['id']
            if sensor_id in last_data['humidity']:
                sensor['value'] = last_data['humidity'][sensor_id]['value']
                humidity_values.append(last_data['humidity'][sensor_id]['value'])

        if len(humidity_values):
            result['med_humidity'] = round(statistics.median(humidity_values), 1)
        result['sensors'] = sensors
        return result

    def get_redis_data(route_id, start, end, delta):
        if not route_id or not start or not end or not delta:
            return None
        route = get_object_or_none(Route, id=int(route_id))
        if not route:
            return None
        sensors = Sensor.get_route_sensors(route_id)
        sensor_ids = [item['id'] for item in sensors]
        delta_labels = {"live": "raw", "daily": "1d", "weekly": "1w", "monthly": "1m"}
        reddb = RedisDB(route.city_id, route.id)
        data = reddb.get_route_range(sensor_ids, start, end, delta_labels[delta])
        return data

class Sensor(BaseModel):

    #id - automatic

    name = CharField()
    code = CharField()
    latitude = FloatField()
    longitude = FloatField()
    route_id = ForeignKeyField(db_column='route_id', null=False, model=Route, to_field='id')

    class Meta:
        db_table = 'sensor'

    def get_route_sensors(route_id):
        if not route_id:
            return None
        sensors = Sensor.select().where(Sensor.route_id==route_id).order_by(Sensor.id).dicts()
        return sensors

    def get_city_sensors(city_id):
        if not city_id:
            return None
        routes = Route.select(Route.id).where(Route.city_id==city_id).dicts()
        route_ids = [x['id'] for x in routes]
        sensors = Sensor.select().where(Sensor.route_id.in_(route_ids)).order_by(Sensor.id).dicts()
        return sensors

    def get_city_sensors_count(city_id):
        if not city_id:
            return None
        routes = Route.select(Route.id).where(Route.city_id==city_id).dicts()
        route_ids = [x['id'] for x in routes]
        sensors = Sensor.select().where(Sensor.route_id.in_(route_ids)).count()
        return sensors
    
    def get_sensor_by_code(code):
        if not code:
            return None
        sensor = Sensor.get(Sensor.code == code).dicts()
        return sensor


    def initialize_new_sensor(route_id, sensor_code):
        if not route_code or not sensor_code:
            return None
        route = get_object_or_none(Route, id=route_id)
        if not route:
            return None
        sensor = Sensor.get(Sensor.code==sensor_code, Sensor.route_id==route_id)
        if sensor:
            return False
        else:
            sensor = Sensor.create(name="New Sensor", code=sensor_code, route_id=route_id)    
        return sensor

    
    
    def handle_received_data(city_code, route_code, data):
        try:
            if not city_code or not route_code or not data:
                return {"result": False}
            city = get_object_or_none(City, code=city_code)
            if not city:
                log.error("Error while processing received data - City code {} not found!!!".format(city_code))
                return {"result": False}
            route = Route.select().where(Route.code == route_code, Route.city_id == city.id).first()
            if not route:
                log.error("Error while processing received data - Route code {} in City {} not found!!!".format(route_code, city_code))
                return {"result": False}
            sensors_data = data['sensors']

            reddb = RedisDB(city.id, route.id)

            reddb.add_temperature(data['temperature'])

            bulk_items = []
            for item in sensors_data:
                sensor = Sensor.select().where(Sensor.route_id == route.id, Sensor.code == item['sensor_code']).first()
                if not sensor:
                    sensor = Sensor.initialize_new_sensor(route.id, item['sensor_code'])
                if not sensor:
                    log.error('Sensor initialization failed')
                bulk_items.append((sensor.id, item['sensor_value']))
                # reddb.add_humidity(sensor.id, item['sensor_value'])
            if bulk_items:
                reddb.add_humidity_bulk(bulk_items)
            set_route_time = Route.set_last_data_time(route.id)
            return {"result": True, "route_id": route.id}
        except Exception as e:
            log.error("Error : {} - City Code: {} - Route Code: {} - Data: {}".format(e, city_code, route_code, data))
            return {"result": False}


# --------------------------------------------------------------------------

if __name__ == '__main__':

    # quick adhoc tests
    logging.basicConfig(level=logging.DEBUG)

    u = User(first_name="tomi")
    u.email = "myemail@example.org"
    u.save(force_insert=True)
    print(u)

    print(list(query_users(0, "10", ".com")))

    print(list(query_movies()))
    print(query_unique_directors())

